######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 18 20:29:40 2008
######################################################################

TEMPLATE = app
TARGET = 
OBJECTS_DIR = build

CONFIG += debug

# Input
HEADERS += LibGroup.h \
           DotLib.h
SOURCES += LibGroup.cpp \
           DotLib.cpp \
           main.cpp

LEXSOURCES += liberty.l
YACCSOURCES += liberty.y

